### PR TITLE
FIX Sanitise data class in 'view imported data history' link so it resolves correctly

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves https://github.com/silverstripe/silverstripe-registry/issues/52

Will need to be merge up as well

### CODE REVIEW

**Comment by NightJar** [comment]
>Will need to be merge up as well

Do you mean to `2`, or to `3.0` and `master` (3.x-dev) also?

**Comment by robbieaverill** [comment]
We don't merge major version branches into patch branches, but 2.0 into 3.0 is fine

**Comment by NightJar** [comment]
I'm confused sorry.
This PR was merged to a patch branch (`2.0`), and `2` would be a minor branch. That merge up is fine, we do that all the time.
So I presume you mean from `2` into `3.0`, which would be a minor branch into a patch branch. Discounting any other unmerged changes between the two, this action would be effectively the same as `2.0` to `3.0`, which you've said is OK.
Does the transition of major release boundaries make this an exception (that it's OK)?

image

**Comment by robbieaverill** [comment]
You can merge 2.0 into 3.0, and 2.0 into 2, but you cannot merge 2 into 3.0 because 2 may contain new features that don't exist in 3.0.x releases already

**Comment by NightJar** [comment]
done :)

**Pull request merged**
